services:
  - type: web
    name: kino-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: your_bot_token_here
      - key: ADMIN_ID
        value: your_admin_id_here